<a href="https://colab.research.google.com/github/Src-Bhavesh/DS-Basics/blob/main/04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy**

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5,6, False])
b = np.array([1,2,3,4,5,6,"2"])
print(type(a))
print(a)
print(b)


<class 'numpy.ndarray'>
[1 2 3 4 5 6 0]
['1' '2' '3' '4' '5' '6' '2']


In [ ]:
na = np.array([1,2,3,'hello',False])
print(bool(na[-1]))

a = False;
print(bool(a))

True
False


In [ ]:
a = np.zeros((2,3,4),dtype=int)     #by default it is float
print(a)

print(type(a[0][0][0]))

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
<class 'numpy.int64'>


In [ ]:
a = np.ones((2,3,4),dtype=int)     #by default it is float
print(a)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [ ]:
a = np.empty((2,3,4),dtype=int)     #by default it is float
print(a)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [ ]:
a= np.full((2,3),5,dtype=int)
print(a)

[[5 5 5]
 [5 5 5]]


In [ ]:
a= np.arange(2,50,2)
print(a)

al = np.linspace(2,10,5)
print(al)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
[ 2.  4.  6.  8. 10.]


In [ ]:
a = np.ones((3,4))
print(a.dtype)
print(a.size)
print(a.shape)

float64
12
(3, 4)


In [ ]:
a = np.random.randint(1,7,4) #start,stop,size
b = np.random.choice([1,2,3,4,5,6,7,8],2)

print(a)
print(b)

[2 3 1 6]
[7 8]


In [ ]:
a = np.array([1,4,6,5])
b = np.array([2,3,7,9])
# b = np.array([2,3,7,9,0])
print(a*2)
print(a+b)
print(a-b)
print(a/b)
print(a*b)

a=[1,2,3,4]
b=[5,6,7,8]
print(a*2)


[ 2  8 12 10]
[ 3  7 13 14]
[-1  1 -1 -4]
[0.5        1.33333333 0.85714286 0.55555556]
[ 2 12 42 45]
[1, 2, 3, 4, 1, 2, 3, 4]


In [ ]:
a = np.random.randint(2,15,6)
print(a)

b=a.reshape((2,3))
print(b)

[10  6 13 13  2 13]
[[10  6 13]
 [13  2 13]]


In [ ]:
a = np.random.randint(2,15,9)
print(a)

b=a.reshape((3,3))
print(b)

c=b.transpose()
print(c)

[ 3  6 12  6 12  8 12 13 14]
[[ 3  6 12]
 [ 6 12  8]
 [12 13 14]]
[[ 3  6 12]
 [ 6 12 13]
 [12  8 14]]


In [ ]:
a = np.random.randint(2,15,9)
b = np.random.randint(2,15,8)

c = np.concatenate((a, b),axis=0)

print(c)

[ 9 11  2  8  8  8  3 13  3  2 12  7 10 13 13  3  4]


In [ ]:
a = np.random.randint(2,15,8)
b = np.random.randint(2,15,8)
print("A = " ,a)
print("B = ",b)

# c = np.where(condition , x , y) if true x otherwisw xy
c = np.where(b>a , b , a)
print(c)

A =  [13 12  6  8 14  6  9 12]
B =  [ 8  4  9 12 12 14  9  8]
[13 12  9 12 14 14  9 12]


In [ ]:
a = np.random.randint(2,15,8)
print(a)
print(np.sum(a))
# b= np.sort(a)
print(np.sort(a))
# c=np.mean(a)
print(np.mean(a))
# d=np.std(a)
print(np.std(a))

print(np.min(a))
print(np.max(a))

print(np.unique(a)) #sort with only unique elemnt


[ 2 11 10  3 13 13  7  2]
61
[ 2  2  3  7 10 11 13 13]
7.625
4.470388685561916
2
13
[ 2  3  7 10 11 13]


In [ ]:
a = np.random.randint(2,25,(4,4))
b = np.random.randint(2,25,(4,4))
print(a)
print(b)

print(np.matmul(a,b))

[[19 13 19  2]
 [18 18 20  3]
 [23  6 12  5]
 [ 7  7 24 20]]
[[11 18 14 23]
 [ 7 10 24 10]
 [24 22 17 12]
 [21 24 22 20]]
[[ 798  938  945  835]
 [ 867 1016 1090  894]
 [ 688  858  780  833]
 [1122 1204 1114  919]]


In [ ]:
# p = np.random.randint(20,100,7)
l=[]
d=['mon','tues','wed','thurs','fri','sat','sun']
for i in range(7):
    l.append(int(input(f'score on {d[i]} ')))
p=np.array(l)
print("Runs = ",p)
print("Total = ",np.sum(p))
print("Average = ",np.mean(p))
print("St. Devation = ",np.std(p))
print("Median = ",np.median(p))27

print("Min = ",np.min(p))
print("Max = ",np.max(p))


score on mon 23
score on tues 45
score on wed 6
score on thurs 


ValueError: invalid literal for int() with base 10: ''