<a href="https://colab.research.google.com/github/Src-Bhavesh/DS-Basics/blob/main/05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:
a = np.random.randint(1,90,(5,5));
print(a)
print("Rowwise mean")
m1 = np.mean(a,axis=1);
print(m1)
print("Columnwise mean")
m2 = np.mean(a,axis=0);
print(m2)

w = np.where(a%2==0,-1,a)
print(w)

for i in range(len(a)):
  for j in range(len(a[i])):
    if(a[i][j]%2==0):
      a[i][j]=-1

print(a)

print("Rowwise Sort")
l1 = np.sort(a,axis=1);
print(l1)
print("Columnwise Sort")
l2 = np.sort(a,axis=0);
print(l2)
print("Sum Rowwise")
s1 = np.sum(a,axis=1);
print(s1)
print("sum rowwise")
s2 = np.sum(a,axis=0);
print(s2)
print("Count columnwise")
c1 = np.count_nonzero(a<0,axis=0)
print(c1)
c1 = np.sum(np.where(a<0,1,0),axis=0)
print(c1)






[[76 62 67 61 53]
 [53 67 57 20  5]
 [28 67 25 67  8]
 [ 3 57 69 49 27]
 [17 53  7 59 72]]
Rowwise mean
[63.8 40.4 39.  41.  41.6]
Columnwise mean
[35.4 61.2 45.  51.2 33. ]
[[-1 -1 67 61 53]
 [53 67 57 -1  5]
 [-1 67 25 67 -1]
 [ 3 57 69 49 27]
 [17 53  7 59 -1]]
[[-1 -1 67 61 53]
 [53 67 57 -1  5]
 [-1 67 25 67 -1]
 [ 3 57 69 49 27]
 [17 53  7 59 -1]]
Rowwise Sort
[[-1 -1 53 61 67]
 [-1  5 53 57 67]
 [-1 -1 25 67 67]
 [ 3 27 49 57 69]
 [-1  7 17 53 59]]
Columnwise Sort
[[-1 -1  7 -1 -1]
 [-1 53 25 49 -1]
 [ 3 57 57 59  5]
 [17 67 67 61 27]
 [53 67 69 67 53]]
Sum Rowwise
[179 181 157 205 135]
sum rowwise
[ 71 243 225 235  83]
Count columnwise
[2 1 0 1 2]
[2 1 0 1 2]


In [5]:
stock = np.random.randint(30,100,(5,5))
print(stock)

demand = np.random.randint(1,100,(5,5))
print(demand)

remaining = stock-demand
print(remaining)

value = np.where(remaining<0,0,remaining)
print(value)

s=np.sum(remaining[remaining<0])
print("Total Shortage : ",s)

c = np.count_nonzero(value==0)
print("Product with zero stock : ",c)

st = np.sort(a,axis=1);
print(st)




[[66 76 70 63 93]
 [44 49 31 61 38]
 [53 34 35 58 42]
 [93 60 51 96 62]
 [57 88 90 51 80]]
[[46  6 47 11 34]
 [96 70 59 44 76]
 [31 89 59 51 48]
 [34 60  8  9 10]
 [36 42 96 88 22]]
[[ 20  70  23  52  59]
 [-52 -21 -28  17 -38]
 [ 22 -55 -24   7  -6]
 [ 59   0  43  87  52]
 [ 21  46  -6 -37  58]]
[[20 70 23 52 59]
 [ 0  0  0 17  0]
 [22  0  0  7  0]
 [59  0 43 87 52]
 [21 46  0  0 58]]
Total Shortage :  -267
Product with zero stock :  10
[[-1 -1 53 61 67]
 [-1  5 53 57 67]
 [-1 -1 25 67 67]
 [ 3 27 49 57 69]
 [-1  7 17 53 59]]


# **PANDAS**

In [21]:
import pandas as pd


file_ = pd.read_csv("./student_data.csv",sep=',')
print(file_.head());
print(file_.tail());
print(file_.describe());


# print(file_)
# pd.DataFrame(file_)

# print(df)




   study_hours  attendance  sleep_hours  internet_usage  \
0            7          56            8               7   
1            4          69            5               3   
2           11          60            7               6   
3            8          99            9               8   
4            5          52            8               6   

   assignments_completed  previous_score  exam_score placement_status  
0                     10              62      100.00           Placed  
1                      8              56      100.00           Placed  
2                     10              45      100.00           Placed  
3                      4              55       90.17           Placed  
4                      8              40       78.82           Placed  
      study_hours  attendance  sleep_hours  internet_usage  \
9995            2          58            9               7   
9996            7          98            6               9   
9997           10          

TypeError: 'tuple' object is not callable